import { readdir, readFile, mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import type { LoadContext, Plugin } from '@docusaurus/types';

export interface AdrLoaderOptions {
  /** Path to the ADR source directory, relative to docusaurus.config.ts. */
  readonly adrSourceDir: string;
  /** Route prefix where ADRs will be mounted. Defaults to `/architecture/adrs`. */
  readonly outputRoute?: string;
}

interface LoadedAdr {
  readonly id: string;
  readonly slug: string;
  readonly title: string;
  readonly status?: string;
  readonly date?: string;
  readonly body: string;
  readonly sourcePath: string;
}

/**
 * Lernkit ADR loader.
 *
 * Reads `docs/adr/*.md` from the repo root and emits one Docusaurus doc per ADR
 * into `apps/website/docs/architecture/adrs/`. Single source of truth: the ADRs
 * live in `docs/adr/` and are picked up here on every build; the rendered
 * Docusaurus pages are gitignored.
 *
 * The plugin runs in `loadContent`, before Docusaurus' content-docs plugin
 * scans the docs directory, so the generated pages participate in the normal
 * sidebar autogeneration pipeline.
 */
export default function adrLoaderPlugin(
  context: LoadContext,
  options: AdrLoaderOptions,
): Plugin<LoadedAdr[]> {
  const sourceDir = resolve(context.siteDir, options.adrSourceDir);
  // Mirror the ADRs into the docs tree so the autogenerated sidebar picks them up.
  const targetDir = resolve(context.siteDir, 'docs/architecture/adrs');

  return {
    name: 'lernkit-adr-loader',

    async loadContent() {
      const entries = await readdir(sourceDir, { withFileTypes: true });
      const mdFiles = entries
        .filter((e) => e.isFile() && e.name.endsWith('.md') && e.name !== 'README.md')
        .map((e) => e.name)
        .sort();

      const adrs: LoadedAdr[] = [];
      for (const filename of mdFiles) {
        const sourcePath = join(sourceDir, filename);
        const raw = await readFile(sourcePath, 'utf8');
        const adr = parseAdr(filename, raw, sourcePath);
        if (adr) adrs.push(adr);
      }
      return adrs;
    },

    async contentLoaded({ content }) {
      if (!content) return;
      await mkdir(targetDir, { recursive: true });

      const indexEntries: string[] = [];
      for (const adr of content) {
        const dest = join(targetDir, `${adr.id}.md`);
        const frontmatter = [
          '---',
          `id: ${adr.id}`,
          `title: ${escapeYaml(adr.title)}`,
          `slug: /architecture/adrs/${adr.id}`,
          `sidebar_label: ${escapeYaml(adr.title.replace(/^ADR-?\d+[:.]?\s*/i, ''))}`,
          'description: ' + escapeYaml(adr.title),
          '---',
          '',
          `> Source: [\`docs/adr/${adr.slug}\`](https://github.com/manykarim/lernkit/blob/main/docs/adr/${adr.slug})`,
          '',
        ].join('\n');
        await writeFile(dest, frontmatter + adr.body, 'utf8');
        indexEntries.push(`- [${adr.title}](/architecture/adrs/${adr.id})`);
      }

      const indexBody = [
        '---',
        'id: index',
        'title: Architecture decisions',
        'slug: /architecture/adrs',
        'sidebar_label: All ADRs',
        '---',
        '',
        '# Architecture decisions',
        '',
        'Lernkit captures non-obvious design decisions as Markdown ADRs (Architecture',
        'Decision Records) following the [MADR](https://adr.github.io/madr/) format. The',
        'records below mirror `docs/adr/` from the repo root; that directory is the',
        'source of truth.',
        '',
        ...indexEntries,
        '',
      ].join('\n');
      await writeFile(join(targetDir, 'index.md'), indexBody, 'utf8');
    },

    async postBuild() {
      // No-op for now; placeholder for future output validation hooks.
    },
  };
}

const FRONTMATTER_RE = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/;

function parseAdr(filename: string, raw: string, sourcePath: string): LoadedAdr | null {
  const id = filename.replace(/\.md$/, '');
  let body = raw;
  let frontmatterTitle: string | undefined;
  let status: string | undefined;
  let date: string | undefined;

  const match = FRONTMATTER_RE.exec(raw);
  if (match) {
    const [, fmRaw, rest] = match;
    body = rest ?? '';
    if (fmRaw) {
      for (const line of fmRaw.split('\n')) {
        const m = /^(\w+):\s*(.+)$/.exec(line.trim());
        if (!m) continue;
        const [, key, value] = m;
        if (!key || !value) continue;
        const v = value.replace(/^["']|["']$/g, '');
        if (key === 'title') frontmatterTitle = v;
        else if (key === 'status') status = v;
        else if (key === 'date') date = v;
      }
    }
  }

  let title = frontmatterTitle;
  if (!title) {
    const headingMatch = /^#\s+(.+)$/m.exec(body);
    if (headingMatch && headingMatch[1]) title = headingMatch[1].trim();
  }
  if (!title) title = id;

  return { id, slug: filename, title, status, date, body: escapeMdxAmbiguities(body), sourcePath };
}

/**
 * MDX 3 treats `<` followed by anything that could start a JSX tag name as the
 * beginning of a JSX expression. Plain prose with text like `<3 hops` or `<150ms`
 * trips the parser. Replace `<` with `&lt;` in those contexts, but leave fenced
 * code blocks alone so real code samples stay intact.
 */
function escapeMdxAmbiguities(input: string): string {
  const lines = input.split('\n');
  let inFence = false;
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    if (raw === undefined) continue;
    if (/^```/.test(raw.trimStart())) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;
    // Escape `<` followed by a digit, whitespace, or end-of-line.
    lines[i] = raw.replace(/<(?=[\d\s]|$)/g, '&lt;');
  }
  return lines.join('\n');
}

function escapeYaml(value: string): string {
  if (/^[\w\s\-:.,!?()'"&]+$/.test(value)) {
    return value.includes(':') ? `"${value.replace(/"/g, '\\"')}"` : value;
  }
  return `"${value.replace(/"/g, '\\"')}"`;
}
