import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  reference: [
    {
      type: 'category',
      label: '📖 Introduction',
      collapsed: false,
      items: [
        'introduction/what-is-lernkit',
        'introduction/quickstart',
        'introduction/concepts',
      ],
    },
    {
      type: 'category',
      label: '🛠️ Authoring',
      items: ['authoring/index'],
    },
    {
      type: 'category',
      label: '📦 Packaging',
      collapsed: false,
      items: [
        'packaging/index',
        'packaging/scorm12',
        'packaging/topology',
        'packaging/lms-portability',
      ],
    },
    {
      type: 'category',
      label: '📊 Tracking',
      collapsed: false,
      items: [
        'tracking/interface',
        'tracking/adapters',
        'tracking/pick-tracker',
      ],
    },
    {
      type: 'category',
      label: '⚙️ Runtime',
      items: ['runtime/index'],
    },
    {
      type: 'category',
      label: '🤖 Robot Framework runner',
      items: ['robot-framework/runnable-robot'],
    },
    {
      type: 'category',
      label: '🧩 Components',
      items: ['components/index'],
    },
    {
      type: 'category',
      label: '🚀 LMS deployment',
      items: ['lms-deployment/index'],
    },
    {
      type: 'category',
      label: '🛡️ Architecture',
      link: { type: 'doc', id: 'architecture/index' },
      items: ['architecture/index'],
    },
    {
      type: 'category',
      label: '👷 Contributing',
      items: ['contributing/index'],
    },
    {
      type: 'category',
      label: '📝 API reference',
      items: [
        {
          type: 'category',
          label: '@lernkit/packagers',
          link: { type: 'generated-index', title: '@lernkit/packagers' },
          items: [{ type: 'autogenerated', dirName: 'api/packagers' }],
        },
        {
          type: 'category',
          label: '@lernkit/tracker',
          link: { type: 'generated-index', title: '@lernkit/tracker' },
          items: [{ type: 'autogenerated', dirName: 'api/tracker' }],
        },
      ],
    },
  ],
};

export default sidebars;
